modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/terrarium-earth/athena/issues"

[[mods]]
    modId = "athena"
    version = "${version}"
    displayName = "Athena"
    displayURL = "https://modrinth.com/mod/athena-ctm"
    logoFile = "icon.png"
    authors = "ThatGravyBoat"
    credits = ""
    description = "Crossplatform Baked Model Loader"

[[mixins]]
    config = "athena.mixins.json"
[[mixins]]
    config = "athena-neoforge.mixins.json"

[[dependencies.athena]]
    modId = "neoforge"
    type="required"
    versionRange = "[20.4.46-beta,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.athena]]
    modId = "minecraft"
    type="required"
    versionRange = "[1.20.4,)"
    ordering = "NONE"
    side = "BOTH"